### ISSUE TITLE
 Failed building wheel for lightgbm（MAC）

### ISSUE THREAD

**Issue by jiang13021** [PKU-DAIR/open-box#57]
**Describe the bug**
I followed the [guide](https://open-box.readthedocs.io/zh_CN/latest/installation/installation_guide.html) and tried to install advanced features. After install SWIG and pyrfr, I input the command `pip install ".[extra]"`, then I got the error msg.
```
INFO:LightGBM:Starting to compile with CMake.
      Traceback (most recent call last):
        File "/private/var/folders/rz/1_fgzbrd27v9ymk2g_155yfc0000gp/T/pip-install-agy0m8zj/lightgbm_1cea5ffda24f4fc4b03fbe3b7bd4f925/setup.py", line 95, in silent_call
          subprocess.check_call(cmd, stderr=log, stdout=log)
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 359, in check_call
          retcode = call(*popenargs, **kwargs)
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 340, in call
          with Popen(*popenargs, **kwargs) as p:
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 858, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1704, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/rz/1_fgzbrd27v9ymk2g_155yfc0000gp/T/pip-install-agy0m8zj/lightgbm_1cea5ffda24f4fc4b03fbe3b7bd4f925/setup.py", line 334, in <module>
          setup(name='lightgbm',
        File "/Users/jiangyzanze/opensource/open-box/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/Users/jiangyzanze/opensource/open-box/venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/Users/jiangyzanze/opensource/open-box/venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/Users/jiangyzanze/opensource/open-box/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/Users/jiangyzanze/opensource/open-box/venv/lib/python3.8/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/Users/jiangyzanze/opensource/open-box/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/Users/jiangyzanze/opensource/open-box/venv/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 360, in run
          self.run_command("install")
        File "/Users/jiangyzanze/opensource/open-box/venv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/Users/jiangyzanze/opensource/open-box/venv/lib/python3.8/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/Users/jiangyzanze/opensource/open-box/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/rz/1_fgzbrd27v9ymk2g_155yfc0000gp/T/pip-install-agy0m8zj/lightgbm_1cea5ffda24f4fc4b03fbe3b7bd4f925/setup.py", line 248, in run
          compile_cpp(use_mingw=self.mingw, use_gpu=self.gpu, use_cuda=self.cuda, use_mpi=self.mpi,
        File "/private/var/folders/rz/1_fgzbrd27v9ymk2g_155yfc0000gp/T/pip-install-agy0m8zj/lightgbm_1cea5ffda24f4fc4b03fbe3b7bd4f925/setup.py", line 198, in compile_cpp
          silent_call(cmake_cmd, raise_error=True, error_msg='Please install CMake and all required dependencies first')
        File "/private/var/folders/rz/1_fgzbrd27v9ymk2g_155yfc0000gp/T/pip-install-agy0m8zj/lightgbm_1cea5ffda24f4fc4b03fbe3b7bd4f925/setup.py", line 99, in silent_call
          raise Exception("\n".join((error_msg, LOG_NOTICE)))
      Exception: Please install CMake and all required dependencies first
      The full version of error log was saved into /Users/jiangyzanze/LightGBM_compilation.log
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lightgbm
  Running setup.py clean for lightgbm
Failed to build lightgbm
```
I checked the "LightGBM_compilation.log" and got 
```
......
#include <omp.h>
         ^~~~~~~
1 error generated.
make[3]: *** [CMakeFiles/_lightgbm.dir/src/boosting/gbdt.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
1 error generated.
make[3]: *** [CMakeFiles/_lightgbm.dir/src/boosting/gbdt_model_text.cpp.o] Error 1
1 error generated.
make[3]: *** [CMakeFiles/_lightgbm.dir/src/boosting/gbdt_prediction.cpp.o] Error 1
1 error generated.
make[3]: *** [CMakeFiles/_lightgbm.dir/src/boosting/boosting.cpp.o] Error 1
make[2]: *** [CMakeFiles/_lightgbm.dir/all] Error 2
make[1]: *** [CMakeFiles/_lightgbm.dir/rule] Error 2
make: *** [_lightgbm] Error 2
......
```

**Additional context**
OS: MacOS
version: 12.5.1

**Comment by jiang13021** [comment]
https://lightgbm.readthedocs.io/en/latest/Installation-Guide.html#macos
It works to me. Hope to put it in the document

**Comment by jhj0411jhj** [comment]
Thanks. We have put it in the documentation.
