### ISSUE TITLE
提供的分布式示例程序 distributed_optimization.py 在Windows下无法运行

### ISSUE THREAD

**Issue by appleman4000** [PKU-DAIR/open-box#61]
command line:
python distributed_optimization.py --role master --n_workers 2 --parallel_strategy async --port 13579

Traceback (most recent call last):
  File "distributed_optimization.py", line 50, in <module>
    opt = DistributedOptimizer(
  File "C:\Users\Administrator\.conda\envs\FutureQuant\lib\site-packages\openbox\utils\util_funcs.py", line 229, in wrapped_func
    return func(*args, **kwargs)
  File "C:\Users\Administrator\.conda\envs\FutureQuant\lib\site-packages\openbox\utils\util_funcs.py", line 229, in wrapped_func
    return func(*args, **kwargs)
  File "C:\Users\Administrator\.conda\envs\FutureQuant\lib\site-packages\openbox\optimizer\message_queue_smbo.py", line 63, in __init__
    self.master_messager = MasterMessager(ip, port, authkey, max_queue_len, max_queue_len)
  File "C:\Users\Administrator\.conda\envs\FutureQuant\lib\site-packages\openbox\core\message_queue\master_messager.py", line 16, in __init__
    self._init_master()
  File "C:\Users\Administrator\.conda\envs\FutureQuant\lib\site-packages\openbox\core\message_queue\master_messager.py", line 24, in _init_master
    manager.start()
  File "C:\Users\Administrator\.conda\envs\FutureQuant\lib\multiprocessing\managers.py", line 579, in start
    self._process.start()
  File "C:\Users\Administrator\.conda\envs\FutureQuant\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Administrator\.conda\envs\FutureQuant\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Administrator\.conda\envs\FutureQuant\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Administrator\.conda\envs\FutureQuant\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'MasterMessager._init_master.<locals>.<lambda>'

**Comment by jhj0411jhj** [comment]
The bug is fixed and will be included in the next release. Thanks for reporting.
