### ISSUE TITLE
AssertionError when I use RandomAdvisor

### ISSUE THREAD

**Issue by jiang13021** [PKU-DAIR/open-box#8]
**Describe the bug**
openbox version: 0.7.16

When I use 
```python
opt = Optimizer(
                branin,
                space,
                max_runs=1,
                advisor_type='random',
                surrogate_type='gp',
                time_limit_per_trial=60,
                task_id="fast_task",
            )
            history = opt.run()
```
I got AssertionError
```
Traceback (most recent call last):
  File "openbox_test.py", line 60, in <module>
    opt = Optimizer(
  File "/lib/python3.8/site-packages/openbox/optimizer/generic_smbo.py", line 188, in __init__
    self.config_advisor = RandomAdvisor(config_space,
  File "/lib/python3.8/site-packages/openbox/core/random_advisor.py", line 28, in __init__
    super().__init__(
  File "/lib/python3.8/site-packages/openbox/core/generic_advisor.py", line 89, in __init__
    self.check_setup()
  File "/lib/python3.8/site-packages/openbox/core/generic_advisor.py", line 177, in check_setup
    assert self.optimization_strategy in ['bo', 'random']
```
I found that when I call RandomAdvisor.\_\_init\_\_(), I will call 
```python
super().__init__(
            config_space, num_objs, num_constraints, initial_trials, initial_configurations,
            init_strategy, history_bo_data, 'random', surrogate_type,
            acq_type, acq_optimizer_type, ref_point, output_dir, task_id, random_state,
            **kwargs,
        )
```
**The 8th parameter is 'random', but it should be the 9th parameter**
Let's see the constructor of its parent class "Advisor.\_\_init\_\_()"
```python
def __init__(self, config_space,
                 num_objs=1,
                 num_constraints=0,
                 initial_trials=3,
                 initial_configurations=None,
                 init_strategy='random_explore_first',
                 history_bo_data=None,
                 rand_prob=0.1,
                 optimization_strategy='bo',
                 surrogate_type='auto',
                 acq_type='auto',
                 acq_optimizer_type='auto',
                 ref_point=None,
                 output_dir='logs',
                 task_id='default_task_id',
                 random_state=None,
                 **kwargs)
```
as you can see, the 8th parameter is "rand_prob" instead of "optimization_strategy"

**you can run the following codes to see the error**

```python
from openbox import sp
from openbox import Optimizer
import numpy as np

space = sp.Space()
x1 = sp.Real("x1", -5, 10, default_value=0)
x2 = sp.Real("x2", 0, 15, default_value=0)
space.add_variables([x1, x2])

# Define Objective Function
def branin(config):
    x1, x2 = config['x1'], config['x2']
    y = (x2-5.1/(4*np.pi**2)*x1**2+5/np.pi*x1-6)**2+10*(1-1/(8*np.pi))*np.cos(x1)+10
    return y


if __name__ == '__main__':
    # Run
    opt = Optimizer(
        branin,
        space,
        max_runs=1,
        advisor_type='random',
        surrogate_type='gp',
        time_limit_per_trial=60,
        task_id='fast_task',
    )
    history = opt.run()
    print(history)
```

**Comment by jhj0411jhj** [comment]
Thanks for the issue. We have fixed the bug and the next version (0.7.17) will be released in the near future. 

If you have urgent needs, please install OpenBox from Github source code. 

We will continue to improve our testing scripts. Any suggestions will be welcomed.
