### ISSUE TITLE
AssertError when I use MCAdvisor

### ISSUE THREAD

**Issue by jiang13021** [PKU-DAIR/open-box#9]
**Describe the bug**
openbox version : 0.7.16
to see the bug, you can run the following code:
```python
from openbox import sp
from openbox import Optimizer
import numpy as np

space = sp.Space()
x1 = sp.Real("x1", -5, 10, default_value=0)
x2 = sp.Real("x2", 0, 15, default_value=0)
space.add_variables([x1, x2])

# Define Objective Function
def branin(config):
    x1, x2 = config['x1'], config['x2']
    y = (x2-5.1/(4*np.pi**2)*x1**2+5/np.pi*x1-6)**2+10*(1-1/(8*np.pi))*np.cos(x1)+10
    return y


if __name__ == '__main__':
    # Run
    opt = Optimizer(
        branin,
        space,
        max_runs=1,
        advisor_type='mcadvisor',
        surrogate_type='gp',
        time_limit_per_trial=60,
        task_id='fast_task',
    )
    history = opt.run()
    print(history)
```
the error report is : 
```
Traceback (most recent call last):
  File "/openbox_test.py", line 78, in <module>
    opt = Optimizer(
  File "/lib/python3.8/site-packages/openbox/optimizer/generic_smbo.py", line 153, in __init__
    self.config_advisor = MCAdvisor(config_space,
  File "/lib/python3.8/site-packages/openbox/core/mc_advisor.py", line 37, in __init__
    super().__init__(config_space,
  File "/lib/python3.8/site-packages/openbox/core/generic_advisor.py", line 89, in __init__
    self.check_setup()
  File "/lib/python3.8/site-packages/openbox/core/mc_advisor.py", line 73, in check_setup
    assert self.acq_type in ['mcei']
AssertionError
```
The problem is that when the Optimizer is constructed, the default value of acq_type is ‘auto’, but in openbox.core.mc_advisor.MCAdvisor#check_setup, it is judged whether acq_type is None.

**Comment by jhj0411jhj** [comment]
Thanks for the issue. We have fixed the bug and the next version (0.7.17) will be released in the near future. 

If you have urgent needs, please install OpenBox from Github source code. 

We will continue to improve our testing scripts. Any suggestions will be welcomed.
